sudo: requered
services:
    - docker
before_install:
    - docker build -t evgenik22/docker-react -f Dockerfile.dev .

script:
    docker run evgenik22/docker-react npm run test -- --coveragei
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-729597639361"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
 
